// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proauto.Data;

#nullable disable

namespace ProAuto.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628231120_AddPhoneToAssociate")]
    partial class AddPhoneToAssociate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proauto.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociateId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssociateId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssociateId = 1,
                            City = "BH",
                            Number = "100",
                            State = "MG",
                            Street = "Rua A",
                            ZipCode = "30100000"
                        },
                        new
                        {
                            Id = 2,
                            AssociateId = 2,
                            City = "BH",
                            Number = "200",
                            State = "MG",
                            Street = "Rua B",
                            ZipCode = "30200000"
                        });
                });

            modelBuilder.Entity("Proauto.Models.Associate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Associates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "11111111111",
                            Name = "João Silva",
                            Phone = "5531988888888"
                        },
                        new
                        {
                            Id = 2,
                            CPF = "22222222222",
                            Name = "Maria Souza",
                            Phone = "5531999999999"
                        });
                });

            modelBuilder.Entity("Proauto.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociateId")
                        .HasColumnType("int");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssociateId")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssociateId = 1,
                            Plate = "ABC1234"
                        },
                        new
                        {
                            Id = 2,
                            AssociateId = 2,
                            Plate = "XYZ9999"
                        });
                });

            modelBuilder.Entity("Proauto.Models.Address", b =>
                {
                    b.HasOne("Proauto.Models.Associate", "Associate")
                        .WithOne("Address")
                        .HasForeignKey("Proauto.Models.Address", "AssociateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Associate");
                });

            modelBuilder.Entity("Proauto.Models.Vehicle", b =>
                {
                    b.HasOne("Proauto.Models.Associate", "Associate")
                        .WithOne("Vehicle")
                        .HasForeignKey("Proauto.Models.Vehicle", "AssociateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Associate");
                });

            modelBuilder.Entity("Proauto.Models.Associate", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
